<a href="https://colab.research.google.com/github/SPThole/LTFS_repo/blob/main/LETSEE_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# !pip install xgboost==1.3.3
# !python -m pip install dask[dataframe] --upgrade
# !pip install dask-xgboost


# !pip install dask_ml
# !pip install shap

In [ ]:
!pip install catboost

In [ ]:
# from dask.distributed import Client

# client = Client(n_workers=4, threads_per_worker=1)
# client

In [ ]:
import pandas as pd
import numpy as np
import datetime
import seaborn as sns
import xgboost as xgb
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score,classification_report,confusion_matrix
import lightgbm
import catboost as catb
from sklearn.model_selection import GridSearchCV, StratifiedKFold
%matplotlib inline

In [ ]:
train = pd.read_csv('/content/drive/MyDrive/trainer_csv6.csv')
test = pd.read_csv('/content/drive/MyDrive/tester_csv6.csv')

In [ ]:
# train['Top-up Month'] = train['Top-up Month'].map({0:0,
#                                                    1:1,
#                                                    2:1,3:1,4:1,5:1,6:1})

In [ ]:
# train = train[train['Top-up Month']!=0]

In [ ]:
# trainer1 = train[[ 'ID','1.0', '2.0', '3.0', '4.0', '5.0',
#        '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0','Top-up Month']]
# tester1 = test[['ID', '1.0', '2.0', '3.0', '4.0', '5.0',
#        '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']]

In [ ]:
train = train.drop(columns=['13.0','14.0','15.0','16.0','17.0','18.0','19.0'])

In [ ]:
test = test.drop(columns=[ '13.0', '14.0','15.0'])

In [ ]:

# train01 = train.copy()
# train01['Top-up Month'] = train01['Top-up Month'].map({0:0,
#                                                    1:1,
#                                                    2:1,3:1,4:1,5:1,6:1})


In [ ]:
# train['Top-up Month'].value_counts(normalize=True), train_y6.value_counts(normalize=True)

In [ ]:
train.columns

Index(['ID', 'EMI', 'ACCT-TYPE', 'CONTRIBUTOR-TYPE', 'OWNERSHIP-IND',
       'ACCOUNT-STATUS', 'ASSET_CLASS', 'SELF-INDICATOR', 'TENURE',
       'Frequency', 'InstlmentMode', 'LoanStatus', 'PaymentMode', 'BranchID',
       'Tenure', 'AssetCost', 'AmountFinance', 'DisbursalAmount',
       'ManufacturerID', 'LTV', 'SEX', 'AGE', 'MonthlyIncome', 'State',
       'Top-up Month', 'DURATION', 'lens', 'how_many_6',
       'REPORTED DATE - HISTm', 'REPORTED DATE - HISTy', 'DisbursalDatem',
       'DisbursalDatey', 'MaturityDAtem', 'MaturityDAtey', '1.0', '2.0', '3.0',
       '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'],
      dtype='object')

In [ ]:
test.head()

ID      EMI  ACCT-TYPE  ...           10.0          11.0          12.0
0    4   1000.0   1.314483  ...            NaN  1.287466e+06  1.238752e+06
1    5   9300.0   1.980461  ...  248177.550000  3.272286e+05  4.288888e+05
2    6  35800.0   1.374217  ...  125562.500000  8.031250e+04  1.092250e+05
3   25  52000.0   1.138935  ...   56385.428571  5.017383e+04  8.587660e+04
4  119  35400.0   1.079124  ...  397700.000000  3.080333e+05  2.267000e+05

[5 rows x 45 columns]

In [ ]:
pd.get_dummies(train['Top-up Month'])

0  1  2  3  4  5  6
0       0  0  0  0  0  0  1
1       1  0  0  0  0  0  0
2       0  1  0  0  0  0  0
3       0  0  0  0  0  0  1
4       0  0  0  0  0  1  0
...    .. .. .. .. .. .. ..
128650  0  0  0  1  0  0  0
128651  1  0  0  0  0  0  0
128652  1  0  0  0  0  0  0
128653  1  0  0  0  0  0  0
128654  1  0  0  0  0  0  0

[128655 rows x 7 columns]

In [ ]:
X, y = train.drop(columns=['ID','Top-up Month']), train['Top-up Month']
Xt = train.drop(columns = 'ID')

In [ ]:
# X01, y01 = train01.drop(columns=['ID','Top-up Month']), train01['Top-up Month']
# Xt01 = train01.drop(columns = 'ID')

# model 0/1

In [ ]:
# X01, y01 = X01.drop(columns=[
#        '2.0','3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']),train01['Top-up Month']
# train_x01, test_x01, train_y01, test_y01 = train_test_split(X01, y01,stratify = y01,test_size=0.2,random_state=42)

# lgb_train = lightgbm.Dataset(train_x01, train_y01)
# lgb_test = lightgbm.Dataset(test_x01, test_y01)

# params = {'boosting_type': 'gbdt',
# 'objective': 'multiclass',
# 'num_class':7,
# 'eval_meric':'mlogerror',
# # 'min_child_weight':5,
# 'n_estimators':250

# # 'class_weight':{0:1/0.829171,
# #                 6:1/0.065027,
# #                 5:1/0.028417,
# #                 3:1/0.027142,
# #                 4:1/0.023800,
# #                 2:1/0.018406,
# #                 1:1/0.008037}
# }

# model1 = lightgbm.train(
# params,
# lgb_train,
# num_boost_round=500,
# valid_sets=[lgb_train, lgb_test],
# early_stopping_rounds=20
# )
# # model1 = lightgbm.LGBMClassifier(**params)
# # model1.fit(train_x1, train_y1)

# print(f1_score(test_y01,
#                model1.predict(test_x01).argmax(axis=1),
#                average='macro'))
# # predss1 = model1.predict(test_x1)
# # # f1 = f1_score(test_y1,predss1,average='macro')
# # print(f1)
# preds1 = model1.predict(test.drop(columns=['ID',
#        '2.0','3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'])).argmax(axis=1)

# X01[['p01','p11','p21','p31','p41','p51','p61']] = model1.predict(X01)
# test[['p01','p11','p21','p31','p41','p51','p61']]= model1.predict(test.drop(columns=['ID',
#        '2.0','3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))



# # X['p1'] = model1.predict(X1)[:,1]
# # test['p1'] = model1.predict(test.drop(columns=['ID',
# #        '2.0','3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))[:,1]



In [ ]:
# print(f1_score(train_y01,
#                model1.predict(train_x01).argmax(axis=1),
#                average='macro'))

In [ ]:
# print(confusion_matrix(test_y01,
#                model1.predict(test_x01).argmax(axis=1),
#                ))

In [ ]:
# pd.Series(y01).value_counts()

In [ ]:
# train = train[train['Top-up Month']!=0]
# X = train.drop(columns = ['ID','Top-up Month'])

# model 1

In [ ]:
X1, y1 = X.drop(columns=[
       '2.0','3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']),train['Top-up Month']
train_x1, test_x1, train_y1, test_y1 = train_test_split(X1, y1,stratify = y1,test_size=0.2,random_state=42)

lgb_train = lightgbm.Dataset(train_x1, train_y1)
lgb_test = lightgbm.Dataset(test_x1, test_y1)

params = {'boosting_type': 'gbdt',
'objective': 'multiclass',
'num_class':7,
'eval_meric':'mlogerror',
# 'min_child_weight':5,


}

model1 = lightgbm.train(
params,
lgb_train,
num_boost_round=500,
valid_sets=[lgb_train, lgb_test],
early_stopping_rounds=10,

)
# model1 = lightgbm.LGBMClassifier(**params)
# model1.fit(train_x1, train_y1)

print(f1_score(test_y1,
               model1.predict(test_x1).argmax(axis=1),
               average='macro'))
# predss1 = model1.predict(test_x1)
# # f1 = f1_score(test_y1,predss1,average='macro')
# print(f1)
preds1 = model1.predict(test.drop(columns=['ID',
       '2.0','3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'])).argmax(axis=1)

X[['p01','p11','p21','p31','p41','p51','p61']] = model1.predict(X1)
test[['p01','p11','p21','p31','p41','p51','p61']]= model1.predict(test.drop(columns=['ID',
       '2.0','3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))



# X['p1'] = model1.predict(X1)[:,1]
# test['p1'] = model1.predict(test.drop(columns=['ID',
#        '2.0','3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))[:,1]



[1]	training's multi_logloss: 0.656405	valid_1's multi_logloss: 0.662699
Training until validation scores don't improve for 10 rounds.
[2]	training's multi_logloss: 0.621532	valid_1's multi_logloss: 0.629875
[3]	training's multi_logloss: 0.59552	valid_1's multi_logloss: 0.605495
[4]	training's multi_logloss: 0.574157	valid_1's multi_logloss: 0.585377
[5]	training's multi_logloss: 0.556518	valid_1's multi_logloss: 0.56907
[6]	training's multi_logloss: 0.541632	valid_1's multi_logloss: 0.555183
[7]	training's multi_logloss: 0.528685	valid_1's multi_logloss: 0.543341
[8]	training's multi_logloss: 0.517478	valid_1's multi_logloss: 0.533274
[9]	training's multi_logloss: 0.507596	valid_1's multi_logloss: 0.524384
[10]	training's multi_logloss: 0.49885	valid_1's multi_logloss: 0.516728
[11]	training's multi_logloss: 0.490989	valid_1's multi_logloss: 0.50985
[12]	training's multi_logloss: 0.483889	valid_1's multi_logloss: 0.50376
[13]	training's multi_logloss: 0.477466	valid_1's multi_logloss:

In [ ]:
print(f1_score(train_y1,
               model1.predict(train_x1).argmax(axis=1),
               average='macro'))

0.5612257261455059


In [ ]:
print(confusion_matrix(test_y1,
               model1.predict(test_x1).argmax(axis=1),
               ))

[[20841    21    37    64    49    41   282]
 [  144    40     7     3     2     1    10]
 [  288     3   138    23     3     1    18]
 [  451     0    11   197    21     5    13]
 [  374     0     1    20   179    18    21]
 [  536     0     0     1    21   103    70]
 [ 1027     0     0     0     1    10   635]]


In [ ]:
pd.Series(preds1).value_counts()

0    14201
6      423
3       41
4       28
5       23
2       22
1        7
dtype: int64

In [ ]:
pd.Series(y1).value_counts()

0    106677
6      8366
5      3656
3      3492
4      3062
2      2368
1      1034
Name: Top-up Month, dtype: int64

# model 2

In [ ]:
X2, y2 = X.drop(columns=[
       '3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']),train['Top-up Month']
train_x2, test_x2, train_y2, test_y2 = train_test_split(X2, y2,stratify = y2,test_size=0.2,random_state=42)

lgb_train = lightgbm.Dataset(train_x2, train_y2)
lgb_test = lightgbm.Dataset(test_x2, test_y2)

params = {'boosting_type': 'gbdt',
'objective': 'multiclass',
'num_class':7,
'eval_meric':'mlogerror',

}

model2 = lightgbm.train(
params,
lgb_train,
num_boost_round=500,
valid_sets=[lgb_train, lgb_test],
early_stopping_rounds=10
)

print(f1_score(test_y2,
               model2.predict(test_x2).argmax(axis=1),
               average='macro'))
# predss1 = model1.predict(test_x1)
# # f1 = f1_score(test_y1,predss1,average='macro')
# print(f1)
preds2 = model2.predict(test.drop(columns=['ID',
       '3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'])).argmax(axis=1)

X[['p02','p12','p22','p32','p42','p52','p62']] = model1.predict(X1)
test[['p02','p12','p22','p32','p42','p52','p62']]= model1.predict(test.drop(columns=['ID',
       '3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))


# X['p2'] = model2.predict(X2)[:,2]
# test['p2'] = model2.predict(test.drop(columns=['ID',
#        '3.0','4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))[:,2]

[1]	training's multi_logloss: 0.554451	valid_1's multi_logloss: 0.64058
Training until validation scores don't improve for 10 rounds.
[2]	training's multi_logloss: 0.504892	valid_1's multi_logloss: 0.607967
[3]	training's multi_logloss: 0.468599	valid_1's multi_logloss: 0.584172
[4]	training's multi_logloss: 0.439849	valid_1's multi_logloss: 0.565694
[5]	training's multi_logloss: 0.416188	valid_1's multi_logloss: 0.550972
[6]	training's multi_logloss: 0.396143	valid_1's multi_logloss: 0.539005
[7]	training's multi_logloss: 0.379042	valid_1's multi_logloss: 0.529168
[8]	training's multi_logloss: 0.364193	valid_1's multi_logloss: 0.520952
[9]	training's multi_logloss: 0.351084	valid_1's multi_logloss: 0.514042
[10]	training's multi_logloss: 0.33961	valid_1's multi_logloss: 0.508169
[11]	training's multi_logloss: 0.329399	valid_1's multi_logloss: 0.503405
[12]	training's multi_logloss: 0.320267	valid_1's multi_logloss: 0.499349
[13]	training's multi_logloss: 0.312037	valid_1's multi_loglo

In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

In [ ]:
confusion_matrix(test_y2,
               model2.predict(test_x2).argmax(axis=1),
               )

array([[20545,    46,    94,   122,    86,   103,   339],
       [  130,    43,     9,     7,     4,     2,    12],
       [  259,     5,   150,    37,     4,     2,    17],
       [  407,     2,    23,   218,    27,     7,    14],
       [  329,     3,     3,    38,   196,    24,    20],
       [  485,     2,     5,     5,    43,   127,    64],
       [  951,     1,     4,    10,     7,    39,   661]])

In [ ]:
confusion_matrix(train_y2,
               model2.predict(train_x2).argmax(axis=1),
               )

array([[83732,    40,   138,   218,   135,   186,   893],
       [   47,   771,     5,     1,     2,     1,     0],
       [  518,     7,  1311,    37,    12,     5,     4],
       [  929,     4,    29,  1784,    35,     6,     7],
       [  846,     0,     5,    60,  1466,    58,    14],
       [ 1279,     1,     1,    14,    48,  1492,    90],
       [ 3132,     0,     5,     4,     7,    53,  3492]])

In [ ]:
print(f1_score(train_y2,
               model2.predict(train_x2).argmax(axis=1),
               average='macro'))

0.764067520199144


In [ ]:
pd.Series(y2).value_counts(),126287/1268

(0    106677
 6      8366
 5      3656
 3      3492
 4      3062
 2      2368
 1      1034
 Name: Top-up Month, dtype: int64, 99.59542586750788)

In [ ]:
pd.Series(preds2).value_counts()

0    13868
6      460
5      126
3       98
2       82
4       79
1       32
dtype: int64

# model3

In [ ]:
X3, y3 = X.drop(columns=[
       '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']),train['Top-up Month']
train_x3, test_x3, train_y3, test_y3 = train_test_split(X3, y3,stratify = y3,test_size=0.2,random_state=42)

lgb_train = lightgbm.Dataset(train_x3, train_y3)
lgb_test = lightgbm.Dataset(test_x3, test_y3)

params = {'boosting_type': 'gbdt',
'objective': 'multiclass',
'num_class':7,
'eval_meric':'mlogerror',
'min_child_weight':50}

model3 = lightgbm.train(
params,
lgb_train,
num_boost_round=500,
valid_sets=[lgb_train, lgb_test],
early_stopping_rounds=10
)

# model3 = lightgbm.LGBMClassifier(n_estimators=250)
# model3.fit(train_x3, train_y3)

print(f1_score(test_y3,
               model3.predict(test_x3).argmax(axis=1),
               average='macro'))
# predss1 = model1.predict(test_x1)
# # f1 = f1_score(test_y1,predss1,average='macro')
# print(f1)
preds3 = model3.predict(test.drop(columns=['ID',
       '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'])).argmax(axis=1)

X[['p03','p13','p23','p33','p43','p53','p63']] = model1.predict(X1)
test[['p03','p13','p23','p33','p43','p53','p63']]= model1.predict(test.drop(columns=['ID',
       '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))


# X['p3'] = model3.predict(X3)[:,3]
# test['p3'] = model3.predict(test.drop(columns=['ID',
#       '4.0', '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))[:,3]

[1]	training's multi_logloss: 0.596025	valid_1's multi_logloss: 0.63997
Training until validation scores don't improve for 10 rounds.
[2]	training's multi_logloss: 0.536436	valid_1's multi_logloss: 0.603429
[3]	training's multi_logloss: 0.49554	valid_1's multi_logloss: 0.578483
[4]	training's multi_logloss: 0.463836	valid_1's multi_logloss: 0.559519
[5]	training's multi_logloss: 0.438297	valid_1's multi_logloss: 0.544471
[6]	training's multi_logloss: 0.417112	valid_1's multi_logloss: 0.532252
[7]	training's multi_logloss: 0.399105	valid_1's multi_logloss: 0.522206
[8]	training's multi_logloss: 0.383506	valid_1's multi_logloss: 0.513837
[9]	training's multi_logloss: 0.369922	valid_1's multi_logloss: 0.506719
[10]	training's multi_logloss: 0.357955	valid_1's multi_logloss: 0.500885
[11]	training's multi_logloss: 0.347331	valid_1's multi_logloss: 0.496019
[12]	training's multi_logloss: 0.337825	valid_1's multi_logloss: 0.491909
[13]	training's multi_logloss: 0.329442	valid_1's multi_loglo

In [ ]:
confusion_matrix(test_y3,
               model3.predict(test_x3).argmax(axis=1),
               )

array([[20555,    46,    94,   116,    85,    96,   343],
       [  132,    41,    10,     6,     4,     4,    10],
       [  259,     7,   153,    28,     5,     4,    18],
       [  402,     4,    26,   220,    26,     9,    11],
       [  318,     4,     2,    38,   201,    31,    19],
       [  482,     2,     1,     5,    40,   132,    69],
       [  961,     1,     1,     7,     7,    40,   656]])

In [ ]:
print(f1_score(train_y3,
               model3.predict(train_x3).argmax(axis=1),
               average='macro'))

0.7459621873034074


In [ ]:
pd.Series(y3).value_counts(),125163/3492

(0    106677
 6      8366
 5      3656
 3      3492
 4      3062
 2      2368
 1      1034
 Name: Top-up Month, dtype: int64, 35.84278350515464)

In [ ]:
pd.Series(preds3).value_counts()

0    13868
6      469
5      136
3      101
4       74
2       69
1       28
dtype: int64

# model4

In [ ]:
X4, y4 = X.drop(columns=[
       '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']),train['Top-up Month']
train_x4, test_x4, train_y4, test_y4 = train_test_split(X4, y4,stratify = y4,test_size=0.2,random_state=42)

lgb_train = lightgbm.Dataset(train_x4, train_y4)
lgb_test = lightgbm.Dataset(test_x4, test_y4)

params = {'boosting_type': 'gbdt',
'objective': 'multiclass',
'num_class':7,
'eval_meric':'mlogerror',
'min_child_weight':50}

model4 = lightgbm.train(
params,
lgb_train,
num_boost_round=500,
valid_sets=[lgb_train, lgb_test],
early_stopping_rounds=10
)

# model4 = lightgbm.LGBMClassifier(n_estimators=250)
# model4.fit(train_x4, train_y4)

print(f1_score(test_y4,
               model4.predict(test_x4).argmax(axis=1),
               average='macro'))
# predss1 = model1.predict(test_x1)
# # f1 = f1_score(test_y1,predss1,average='macro')
# print(f1)
preds4 = model4.predict(test.drop(columns=['ID',
       '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'])).argmax(axis=1)

X[['p04','p14','p24','p34','p44','p54','p64']] = model1.predict(X1)
test[['p04','p14','p24','p34','p44','p54','p64']]= model1.predict(test.drop(columns=['ID',
        '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))


# X['p4'] = model4.predict(X4)[:,4]
# test['p4'] = model4.predict(test.drop(columns=['ID',
#        '5.0', '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))[:,4]

[1]	training's multi_logloss: 0.596021	valid_1's multi_logloss: 0.639928
Training until validation scores don't improve for 10 rounds.
[2]	training's multi_logloss: 0.536424	valid_1's multi_logloss: 0.603393
[3]	training's multi_logloss: 0.495514	valid_1's multi_logloss: 0.578474
[4]	training's multi_logloss: 0.46379	valid_1's multi_logloss: 0.55945
[5]	training's multi_logloss: 0.438233	valid_1's multi_logloss: 0.544314
[6]	training's multi_logloss: 0.416912	valid_1's multi_logloss: 0.532068
[7]	training's multi_logloss: 0.398945	valid_1's multi_logloss: 0.522062
[8]	training's multi_logloss: 0.383303	valid_1's multi_logloss: 0.513744
[9]	training's multi_logloss: 0.369735	valid_1's multi_logloss: 0.506644
[10]	training's multi_logloss: 0.357788	valid_1's multi_logloss: 0.50088
[11]	training's multi_logloss: 0.347192	valid_1's multi_logloss: 0.496025
[12]	training's multi_logloss: 0.337762	valid_1's multi_logloss: 0.49192
[13]	training's multi_logloss: 0.329276	valid_1's multi_logloss

In [ ]:
print(f1_score(train_y4,
               model4.predict(train_x4).argmax(axis=1),
               average='macro'))

0.747183796649273


In [ ]:
confusion_matrix(test_y4,
               model4.predict(test_x4).argmax(axis=1),
               )

array([[20546,    46,    91,   116,    87,   104,   345],
       [  133,    41,    10,     5,     5,     3,    10],
       [  260,     7,   150,    30,     5,     4,    18],
       [  398,     3,    26,   224,    27,     8,    12],
       [  319,     3,     3,    38,   200,    31,    19],
       [  480,     2,     1,     6,    40,   135,    67],
       [  946,     1,     1,     8,     6,    42,   669]])

In [ ]:
pd.Series(y4).value_counts(),125593/3062

(0    106677
 6      8366
 5      3656
 3      3492
 4      3062
 2      2368
 1      1034
 Name: Top-up Month, dtype: int64, 41.0166557805356)

In [ ]:
pd.Series(preds1).value_counts()

0    14201
6      423
3       41
4       28
5       23
2       22
1        7
dtype: int64

# model5

In [ ]:
X5, y5 = X.drop(columns=[
       '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']),train['Top-up Month']
train_x5, test_x5, train_y5, test_y5 = train_test_split(X5, y5,stratify = y5,test_size=0.2,random_state=42)

lgb_train = lightgbm.Dataset(train_x5, train_y5)
lgb_test = lightgbm.Dataset(test_x5, test_y5)

params = {'boosting_type': 'gbdt',
'objective': 'multiclass',
'num_class':7,
'eval_meric':'mlogerror',
'min_child_weight':50}

model5 = lightgbm.train(
params,
lgb_train,
num_boost_round=500,
valid_sets=[lgb_train, lgb_test],
early_stopping_rounds=10
)

# model5 = lightgbm.LGBMClassifier(n_estimators=250)
# model5.fit(train_x5, train_y5)

print(f1_score(test_y5,
               model5.predict(test_x5).argmax(axis=1),
               average='macro'))
# predss1 = model1.predict(test_x1)
# # f1 = f1_score(test_y1,predss1,average='macro')
# print(f1)
preds5 = model5.predict(test.drop(columns=['ID',
       '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'])).argmax(axis=1)

X[['p05','p15','p25','p35','p45','p55','p65']] = model1.predict(X1)
test[['p05','p15','p25','p35','p45','p55','p65']]= model1.predict(test.drop(columns=['ID',
      '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))
# X['p5'] = model5.predict(X5)[:,5]
# test['p5'] = model5.predict(test.drop(columns=['ID',
#        '6.0', '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))[:,5]

[1]	training's multi_logloss: 0.596005	valid_1's multi_logloss: 0.639907
Training until validation scores don't improve for 10 rounds.
[2]	training's multi_logloss: 0.536305	valid_1's multi_logloss: 0.603465
[3]	training's multi_logloss: 0.495284	valid_1's multi_logloss: 0.578455
[4]	training's multi_logloss: 0.463505	valid_1's multi_logloss: 0.559493
[5]	training's multi_logloss: 0.437963	valid_1's multi_logloss: 0.544316
[6]	training's multi_logloss: 0.416751	valid_1's multi_logloss: 0.532032
[7]	training's multi_logloss: 0.398648	valid_1's multi_logloss: 0.5218
[8]	training's multi_logloss: 0.383059	valid_1's multi_logloss: 0.513538
[9]	training's multi_logloss: 0.369462	valid_1's multi_logloss: 0.506492
[10]	training's multi_logloss: 0.357577	valid_1's multi_logloss: 0.500574
[11]	training's multi_logloss: 0.346868	valid_1's multi_logloss: 0.495643
[12]	training's multi_logloss: 0.337396	valid_1's multi_logloss: 0.491621
[13]	training's multi_logloss: 0.329027	valid_1's multi_loglo

In [ ]:
confusion_matrix(test_y5,
               model5.predict(test_x5).argmax(axis=1),
               )

array([[20579,    45,    89,   114,    83,    96,   329],
       [  132,    41,    11,     6,     4,     3,    10],
       [  258,     7,   153,    30,     5,     4,    17],
       [  397,     4,    25,   224,    27,     8,    13],
       [  322,     3,     3,    38,   196,    30,    21],
       [  483,     2,     2,     5,    38,   133,    68],
       [  966,     1,     1,     8,     5,    39,   653]])

In [ ]:
print(f1_score(train_y5,
               model5.predict(train_x5).argmax(axis=1),
               average='macro'))

0.7458526394730792


In [ ]:
pd.Series(y5).value_counts(),124999/3656

(0    106677
 6      8366
 5      3656
 3      3492
 4      3062
 2      2368
 1      1034
 Name: Top-up Month, dtype: int64, 34.19009846827134)

In [ ]:
pd.Series(preds5).value_counts()

0    13896
6      458
5      131
3      100
4       68
2       66
1       26
dtype: int64

# model6

In [ ]:
X6, y6 = X.drop(columns=[
       '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']),train['Top-up Month']
train_x6, test_x6, train_y6, test_y6 = train_test_split(X6, y6,stratify = y6,test_size=0.2,random_state=42)

lgb_train = lightgbm.Dataset(train_x6, train_y6)
lgb_test = lightgbm.Dataset(test_x6, test_y6)

params = {'boosting_type': 'gbdt',
'objective': 'multiclass',
'num_class':7,
'eval_meric':'mlogerror',
'min_child_weight':50}

model6 = lightgbm.train(
params,
lgb_train,
num_boost_round=500,
valid_sets=[lgb_train, lgb_test],
early_stopping_rounds=10
)

# model6 = lightgbm.LGBMClassifier(n_estimators=250)
# model6.fit(train_x6, train_y6)

print(f1_score(test_y6,
               model6.predict(test_x6).argmax(axis=1),
               average='macro'))
# predss1 = model1.predict(test_x1)
# # f1 = f1_score(test_y1,predss1,average='macro')
# print(f1)
preds6 = model6.predict(test.drop(columns=['ID',
       '7.0', '8.0', '9.0', '10.0', '11.0', '12.0'])).argmax(axis=1)

X[['p06','p16','p26','p36','p46','p56','p66']] = model1.predict(X1)
test[['p06','p16','p26','p36','p46','p56','p66']]= model1.predict(test.drop(columns=['ID',
      '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))


# X['p6'] = model6.predict(X6)[:,6]
# test['p6'] = model6.predict(test.drop(columns=['ID',
#        '7.0', '8.0', '9.0', '10.0', '11.0', '12.0']))[:,6]

[1]	training's multi_logloss: 0.596055	valid_1's multi_logloss: 0.639852
Training until validation scores don't improve for 10 rounds.
[2]	training's multi_logloss: 0.536309	valid_1's multi_logloss: 0.603282
[3]	training's multi_logloss: 0.495233	valid_1's multi_logloss: 0.578288
[4]	training's multi_logloss: 0.463444	valid_1's multi_logloss: 0.559339
[5]	training's multi_logloss: 0.437911	valid_1's multi_logloss: 0.544153
[6]	training's multi_logloss: 0.416627	valid_1's multi_logloss: 0.531961
[7]	training's multi_logloss: 0.398563	valid_1's multi_logloss: 0.521647
[8]	training's multi_logloss: 0.382905	valid_1's multi_logloss: 0.513311
[9]	training's multi_logloss: 0.369289	valid_1's multi_logloss: 0.506161
[10]	training's multi_logloss: 0.357369	valid_1's multi_logloss: 0.5003
[11]	training's multi_logloss: 0.346693	valid_1's multi_logloss: 0.495404
[12]	training's multi_logloss: 0.33725	valid_1's multi_logloss: 0.491316
[13]	training's multi_logloss: 0.328875	valid_1's multi_loglos

In [ ]:
confusion_matrix(test_y6,
               model6.predict(test_x6).argmax(axis=1),
               )

array([[20590,    43,    89,   111,    80,    96,   326],
       [  135,    41,     9,     7,     4,     2,     9],
       [  261,     7,   152,    30,     5,     3,    16],
       [  402,     4,    26,   219,    27,     7,    13],
       [  322,     4,     2,    37,   196,    32,    20],
       [  482,     2,     1,     4,    39,   135,    68],
       [  964,     1,     1,     7,     5,    40,   655]])

In [ ]:
print(f1_score(train_y6,
               model6.predict(train_x6).argmax(axis=1),
               average='macro'))

0.7469380959453508


In [ ]:
pd.Series(y6).value_counts(),120289/8366

(0    106677
 6      8366
 5      3656
 3      3492
 4      3062
 2      2368
 1      1034
 Name: Top-up Month, dtype: int64, 14.378316997370309)

In [ ]:
pd.Series(preds1).value_counts()

0    14201
6      423
3       41
4       28
5       23
2       22
1        7
dtype: int64

# model 0

In [ ]:
X0, y0 = X.drop(columns=[
       '8.0', '9.0', '10.0', '11.0', '12.0']),train['Top-up Month']
train_x0, test_x0, train_y0, test_y0 = train_test_split(X0, y0,stratify = y0,test_size=0.2,random_state=42)

lgb_train = lightgbm.Dataset(train_x0, train_y0)
lgb_test = lightgbm.Dataset(test_x0, test_y0)

params = {'boosting_type': 'gbdt',
'objective': 'multiclass',
'num_class':7,
'eval_meric':'mlogerror',
'min_child_weight':50}

model0 = lightgbm.train(
params,
lgb_train,
num_boost_round=500,
valid_sets=[lgb_train, lgb_test],
early_stopping_rounds=10
)

# model0 = lightgbm.LGBMClassifier(n_estimators=250)
# model0.fit(train_x0, train_y0)

print(f1_score(test_y0,
               model0.predict(test_x0).argmax(axis=1),
               average='macro'))
# predss1 = model1.predict(test_x1)
# # f1 = f1_score(test_y1,predss1,average='macro')
# print(f1)
preds0 = model0.predict(test.drop(columns=['ID',
       '8.0', '9.0', '10.0', '11.0', '12.0'])).argmax(axis=1)

# X['p0'] = model0.predict_proba(X0)[:,0]
# test['p0'] = model0.predict_proba(test.drop(columns=['ID',
#        '8.0', '9.0', '10.0', '11.0', '12.0']))[:,1]

[1]	training's multi_logloss: 0.596051	valid_1's multi_logloss: 0.639685
Training until validation scores don't improve for 10 rounds.
[2]	training's multi_logloss: 0.536312	valid_1's multi_logloss: 0.603019
[3]	training's multi_logloss: 0.495242	valid_1's multi_logloss: 0.578056
[4]	training's multi_logloss: 0.463452	valid_1's multi_logloss: 0.559029
[5]	training's multi_logloss: 0.437854	valid_1's multi_logloss: 0.543819
[6]	training's multi_logloss: 0.416638	valid_1's multi_logloss: 0.531534
[7]	training's multi_logloss: 0.398443	valid_1's multi_logloss: 0.521299
[8]	training's multi_logloss: 0.38276	valid_1's multi_logloss: 0.512857
[9]	training's multi_logloss: 0.369128	valid_1's multi_logloss: 0.505833
[10]	training's multi_logloss: 0.357204	valid_1's multi_logloss: 0.499895
[11]	training's multi_logloss: 0.346473	valid_1's multi_logloss: 0.49501
[12]	training's multi_logloss: 0.336949	valid_1's multi_logloss: 0.490863
[13]	training's multi_logloss: 0.32845	valid_1's multi_loglos

In [ ]:
confusion_matrix(test_y0,
               model0.predict(test_x0).argmax(axis=1),
               )

array([[20585,    43,    89,   115,    84,    99,   320],
       [  131,    41,    11,     6,     5,     3,    10],
       [  263,     6,   151,    32,     5,     2,    15],
       [  402,     4,    26,   222,    26,     7,    11],
       [  323,     4,     3,    37,   196,    31,    19],
       [  484,     2,     3,     5,    38,   136,    63],
       [  955,     1,     1,     7,     5,    40,   664]])

In [ ]:
print(f1_score(train_y0,
               model0.predict(train_x0).argmax(axis=1),
               average='macro'))

0.7460332710748727


In [ ]:
pd.Series(y0).value_counts()

0    106677
6      8366
5      3656
3      3492
4      3062
2      2368
1      1034
Name: Top-up Month, dtype: int64

In [ ]:
predst = pd.Series(dfn['predf'])

In [ ]:
# preds = encode.inverse_transform(preds)
trgt_inv_maps = {6:' > 48 Months', 
             0:'No Top-up Service', 
            1: '12-18 Months',
              5:'36-48 Months', 
              2:'18-24 Months', 
              3:'24-30 Months', 
              4:'30-36 Months'}
predst = predst.map(trgt_inv_maps)

In [ ]:
preds_csv = pd.read_csv('/content/drive/MyDrive/sample_submission_ejm25Dc.csv')

In [ ]:
preds_csv['Top-up Month'] = predst.values

In [ ]:
preds_csv.to_csv('PREDICTION_FILE45.csv',index=None)

In [ ]:
preds_csv['Top-up Month'].value_counts()

No Top-up Service    13941
 > 48 Months           521
24-30 Months           100
36-48 Months            84
30-36 Months            55
18-24 Months            35
12-18 Months             9
Name: Top-up Month, dtype: int64

# Stacked

In [ ]:
# df = pd.DataFrame()
# df['0'] = preds0
# df['1'] = preds1
# df['2'] = preds2
# df['3'] = preds3
# df['4'] = preds4
# df['5'] = preds5
# df['6'] = preds6

In [ ]:
# df = pd.DataFrame()
# df['0'] = model0.predict(test_x0)
# df['1'] = model1.predict(test_x1)
# df['2'] = model2.predict(test_x2)
# df['3'] = model3.predict(test_x3)
# df['4'] = model4.predict(test_x4)
# df['5'] = model5.predict(test_x5)
# df['6'] = model6.predict(test_x6)

In [ ]:
# df1 = pd.DataFrame()
# df1['0'] = test_y0
# df1['1'] = test_y1
# df1['2'] = test_y2
# df1['3'] = test_y3
# df1['4'] = test_y4
# df1['5'] = test_y5
# df1['6'] = test_y6

In [ ]:
# def preder(x):
#   pred = []
  
#   if x['1']==1:
#     pred.append(1)
#   if x['2']==1:
#     pred.append(2)
#   if x['3']==1:
#     pred.append(3)
#   if x['4']==1:
#     pred.append(4)
#   if x['5']==1:
#     pred.append(5)
#   if x['6']==1:
#     pred.append(6)
#   if len(pred)!=0:
#     return min(pred)
#   else:
#     return 0

In [ ]:
preds0 = np.floor(dfn.mean(axis=1))

In [ ]:
dfn = pd.DataFrame()
dfn['preds0'] = preds0
dfn['preds1'] = preds1
dfn['preds2'] = preds2
dfn['preds3'] = preds3
dfn['preds4'] = preds4
dfn['preds5'] = preds5
dfn['preds6'] = preds6

In [ ]:
dfn['predf'] = 0

In [ ]:
dfn.loc[dfn['preds1']==1,'predf'] = 1
dfn.loc[dfn['preds2']==2,'predf'] = 2
dfn.loc[dfn['preds3']==3,'predf'] = 3
dfn.loc[dfn['preds4']==4,'predf'] = 4
dfn.loc[dfn['preds5']==5,'predf'] = 5
dfn.loc[dfn['preds6']==6,'predf'] = 6

In [ ]:
dfn['predf'].value_counts()

0    13889
6      465
5      131
3      100
2       77
4       76
1        7
Name: predf, dtype: int64